title: Darren Goulden
email: ping@darren.gdn
description: >- # this means to ignore newlines until "baseurl:"
  I am Technical Support Engineer working in the UK for Pexip AS based in Norway.
  The main focus of this site is to provide technical guides and information for extended troubleshooting.
  Content is delivered as-is for informational purposes only. Opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darren.gdn" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year/:month/:day/:title:output_ext

github_username:  darrengoulden
linkedin_username: darrengoulden

# Homepage limit posts
number_of_posts: 10

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Disqus Comments
disqus:
  shortname: darrendgn

# Analytics
google_analytics: UA-177327958-1

# Excludes
exclude:
  - changelog.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/

# External links
extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: []