title: Darren Goulden
email: ping@darren.gdn
description: >- # this means to ignore newlines until "baseurl:"
  Darren Goulden is a Technical Support Engineer working in the UK for Pexip AS based in Norway.
  The main focus of this site is to provide technical guides and information for extended troubleshooting.
  Content is delivered as-is for informational purposes only. Opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darren.gdn" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year/:month/:day/:title:output_ext

github_username:  darrengoulden
linkedin_username: darrengoulden

# Homepage limit posts
number_of_posts: 10

# Build settings
# Removed minima theme - now using a regular theme
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Disqus Comments
disqus:
  shortname: darrendgn